### PR TITLE
Clarify multiple type support

### LINKED ISSUE #33: Function names when deriving for multiple types are not descriptive
I am interested in using `goderive` for https://github.com/twpayne/go-geom which exports multiple distinct types.

Some packages may wish to derive functions for multiple types, for example:

```go
package main

type MyFirstStruct struct {
	Int64 int64
}

func (this *MyFirstStruct) Equal(that *MyFirstStruct) bool {
	return deriveEqual(this, that)
}

type MySecondStruct struct {
	StringPtr *string
}

func (this *MySecondStruct) Equal(that *MySecondStruct) bool {
	return deriveEqual(this, that)
}
```

In this case, there is an obvious conflict: `deriveEqual` cannot be overloaded to support both types.

Running `goderive -autoname` resolves this conflict:

```
$ goderive -autoname .
changing function call name from deriveEqual to deriveEqual_
```

The function names `derivedEqual` and `derivedEqual_` are not particularly descriptive and easily misread or mis-typed. Instead they should include the name of the type, e.g. `deriveEqual_MyFirstStruct` and `deriveEqual_MySecondStruct`.

### PR DESCRIPTION
**Pull request by twpayne**
Fixes #33.

### CODE REVIEW

**Comment by awalterschulze** [comment]
Sorry this is just a personal gripe.  Could we some other names and not `Foo` and `Bar`.
Earlier in the Readme I used `MyStruct`, we could reuse that or rather have `ThisStruct` or `ThatType` or something like that.  
Every time, I see `Foo` and `Bar` my eyes start swimming.

But the actual content of what you wrote looks perfect :)

**Comment by twpayne** [comment]
Updated to use `MyStruct` and `MySecondStruct`.

**Comment by awalterschulze** [comment]
Looks good. Technically you could use any suffix, but I think this is the patten that I would like to promote :)

**Comment by awalterschulze** [comment]
Thank you very much :)

**Pull request merged**
