### PR TITLE
add support for go modules

### PR DESCRIPTION
**Pull request by jbl428**
Hi. Thank you for making this program. I love goderive. I always use this for all project. 
I want to contribute and I found that it use deprecated govendor.
so I change some files to support go modules and it success tests (make travis on go version 1.16). 
Please review this pull request.

### CODE REVIEW

**Comment by awalterschulze** [comment]
We lost our CI, since we haven't moved to github actions yet.  This has caused me to delay reviewing this diff, sorry about that.

Maybe as an intermittent step, may I ask if you have run `make travis` and whether this passes?

**Comment by awalterschulze** [comment]
Otherwise it looks like you have been thorough and I would like to merge this.  What do you think?

**Comment by awalterschulze** [comment]
Thank you for going out of your way to fix this.  Always great to hear about people enjoying to use this project :)

**Comment by jbl428** [comment]
I have run `make travis` and it have passed in go version 1.16.
I have tried old go version (1.13) and it builds well but failed some tests.
I think this is because deleted `vendor/vendor.json` file or missing `GO111MODULE=on` env
Should i check older go versions (not supported `go modules`) if it builds successfully?

**Comment by jbl428** [comment]
I have already run `make travis` and it haved passed. (go version 1.16).

But I'm afraid there might be compatibility issues.

I think I should change go version(`1.16`) in `go.mod` file for older go versions.

so, I want to go over one more and I will update this review.

**Comment by awalterschulze** [comment]
I think it is okay to only support the newest version of go, because people can "vendor" an older version.  What do you think?

**Comment by jbl428** [comment]
Yeah, You are right. and I found that it builds well on old version (1.11) even if latest version specified in `go.mod`.  😄 

And I think it would be better to give some version tag to this project. then people can choose the right version.

**Comment by awalterschulze** [comment]
I agree, but to release a version, I think we should first fix the CI, but then that sounds like a great idea.

**Comment by awalterschulze** [comment]
So are you happy if we merge this pull request?

**Comment by jbl428** [comment]
Yes. Please accept this pull request. 

Thank you for reviewing. 👍

**Pull request merged**
