### PR TITLE
fix for issue #60

### LINKED ISSUE #60: deriveSorted does not handle type aliases for elements
Consider the following program
```
package main

import (
    "fmt"
)

type X struct {}

type Y int

type Z map[Y]*X

func test(z Z) {
    for _, k := range deriveSorted(deriveKeys(z)) {
        fmt.Println(z[k])
    }
}

func main() {
    z := map[Y]*X{}
    test(z)
    fmt.Println("Succes")
}
```
Running `goderive` runs fine, but subsequently the program fails to compile, with the following error:
```
./derived.gen.go:11:11: cannot use list (type []Y) as type []int in argument to sort.Ints
```
`deriveSorted` has been generated as:
```
func deriveSorted(list []Y) []Y {
	sort.Ints(list)
	return list
}
```
and it is sort.Ints that is throwing the error

### PR DESCRIPTION
**Pull request by jbl428**
Fixes #60

`deriveSorted` uses `Strings`, `Float64s` and `Ints` functions of `sort` package only if type of the slice element is not aliased.

There is another issue in #60. the author provided some test code. 

```go
type stringalias string

func TestSortedMapKeysTypeAliasKey(t *testing.T) {
    var m map[stringalias]string
    m = random(m).(map[stringalias]string)
    keys := deriveSortedAlias(deriveKeysForMapAliasToString(m))
```

`deriveSortedAlias` is not generated.

I have found that `deriveSortedAlias` never generated if the function's arg is the return value of any generated `goderive` function.

the following test code passes without any issue.

```go
type stringalias string

func TestSortedMapKeysTypeAliasKey(t *testing.T) {
    keys := deriveSortedAlias([]stringalias{"a", "b"})
```

After some testing, I have finally found that if type alias is defined in a normal go file, there is no issue at all.

so, I move the type definitions in `test/normal/*_test.go` files to new `types.go` file.

### CODE REVIEW

**Comment by awalterschulze** [comment]
Now I really need CI back, to be able to properly review this.
I hope it is okay to have a delay here, since I am moving in the next couple of weeks, so things are a bit hectic.

**Comment by jbl428** [comment]
No problem. you can review this anytime you want. 😃 

In the meantime, Is there anything that I can help rebuilding CI?

I have little experience of Github action, but I think I can manage somehow.

**Comment by awalterschulze** [comment]
I have not setup a github action myself either.
If you are willing to help setup the github action, that would be amazing.

Here are some examples for setting up CI with github actions on other go projects:
 - https://github.com/awalterschulze/gominikanren/blob/master/.github/workflows/go.yaml
 - https://github.com/awalterschulze/gographviz/blob/master/.github/workflows/build.yaml
 - https://github.com/goccmack/gocc/blob/master/.github/workflows/build.yaml

What we want is to effectively do something similar to `make travis`
Does that make sense?

**Comment by jbl428** [comment]
I understand. the examples is useful for building CI.  Thank you.

I have one question.

Should I close this PR and reopen it after CI is restored?
I can not sure that  I should request other PR about rebuilding CI and request this one after it merged.

**Comment by awalterschulze** [comment]
You can leave this one open. Let’s see what happens. It might be as simple
as pushing one new commit to this PR to trigger the action once the action
has been merged.

But also whatever is easiest for you

**Comment by jbl428** [comment]
I have added a commit of updating CI badge in `Readme.md`

**Review by awalterschulze — APPROVED** [review]
Thank you.  This looks like a great upgrade.

Still concerned about the fact that we needed to move types to their own go file, but your change doesn't seem to regress that issue and fixes another issue.

**Pull request merged**
