### PR TITLE
spelling mistake

### PR DESCRIPTION
**Pull request by soniah**
spelling mistake

### CODE REVIEW

**Comment by awalterschulze** [comment]
Thanks for finding this mistake :)

The Readme is generated from the code to make sure that it is perfectly representative of the code.  To properly make this fix you will have to correct the `.go` file and run `make` in the root folder.

Or I can do it, your choice, but either way I want this correction :)

**Comment by soniah** [comment]
I was looking through other code and noticed the same spelling mistake, I was wondering about auto-generated code. So I'll leave that stuff to you ;-)

I've been enjoying your article https://awalterschulze.github.io/blog/post/sum-types-over-multiple-returns/ and looking at the ideas in your library. I learned Haskell a few years ago and I'm drifting back towards it...

**Comment by awalterschulze** [comment]
Fixed https://github.com/awalterschulze/goderive/commit/544f7cf4181e572572bf50080219b1b63bf9d4ba

Thank you, it is great to hear that someone is reading my writings :)

How far did you get with your previous Haskell journey?

**Comment by soniah** [comment]
Several years ago I did [Tony Morris's 3 day course](https://github.com/tonymorris/fp-course) and was starting to understand Haskell at a deeper level. But then life came along and threw a few twisters.

I've been competing on https://www.codingame.com/ and finding Go limiting. I want type safety but I also I want to throw out quick (functional) one liners that take a page of Go code. And let's not talk about generics.

So I'm back looking at functional languages. Kotlin for the moment as it's "good enough" and is JVM (useful for work). And I'm pondering Scala/Haskell/Rust.

**Pull request closed without merging**
