### PR TITLE
allow a custom map type to declare DeepCopy func

### PR DESCRIPTION
**Pull request by ndeloof**
This PR allows a type alias (`type foo map[string]bar`) to declare a custom `DeepCopy` method

### CODE REVIEW

**Comment by awalterschulze** [comment]
All paths have changed, so I don't think this will work

**Comment by ndeloof** [comment]
I had to change go module source so I can use my fork in compose-go
the relevant changes are in https://github.com/awalterschulze/goderive/pull/87/files#diff-42a8d5346bcda44c10315b1471d62a3a2cf7800840bfe6e51ac1724e51a52871L372-R394

**Comment by awalterschulze** [comment]
To make a pull request, you would need to fix the paths

**Comment by ndeloof** [comment]
created another PR from a branch

**Pull request closed without merging**
