### PR TITLE
allow a custom map type to declare DeepCopy func

### PR DESCRIPTION
**Pull request by ndeloof**
supersede https://github.com/awalterschulze/goderive/pull/87

### CODE REVIEW

**Comment by awalterschulze** [comment]
Looks good in principle.

Would you like to add a test?

**Comment by ndeloof** [comment]
sure, will do as soon as I can find some spare time for it

**Comment by ndeloof** [comment]
test case added

**Comment by awalterschulze** [comment]
Awesome job, thank you so much :D

**Pull request merged**
